### ISSUE TITLE
What should the Dockerfile include?

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/interledger-rs#165]
Should we keep the Dockerfile in the repo for now or take it out as proposed in https://github.com/emschwartz/interledger-rs/pull/157?

If we keep the Dockerfile, should it include the:
- Interledger.rs CLI / "node" bundle
- settlement engines
- `redis-server`
- `localtunnel` or something similar

I think that in the future we'll want an image that includes the `node`, all of the settlement engines, and redis and/or a postgres db. However, since the settlement pieces aren't ready, is it worth having such a bundle now? We could have a very simple `Dockerfile` that only builds the core interledger.rs binary, but I'm not sure how useful that is. (Also, if we do that, should it include Redis or expect you to have another container running Redis?)

Thoughts?

cc @Neil-Jubinville @gakonst @bstrie @dora-gt

**Comment by Neil-Jubinville** [comment]
My dev needs load out would be

- Interledger.rs CLI / "node" bundle
- redis-server
- localtunnel  OPTIONAL ENV VAR ENABLED

I would prefer **settlement engines stand alongside the ILP node on their own**.

**Comment by dora-gt** [comment]
Hmmm I think we don't need docker files at least for now because the `.sh`s are useful enough and eventually we'll have to redesign the structure, considering scaling.

Or... why don't we create the **interledger.rs website** and analyze the drop-rate (is the word understandable? a common word in Japan🤔) or gather comments on it of whether the explanation is understandable or not.

Of course, the cost could be controversy but I think it is worth arguing because, for the prosperity of ILP and interledger.rs, I think we should place emphasis on Developer Experience.
