### ISSUE TITLE
Should we change any of the HTTP API endpoints?

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/interledger-rs#258]
For example:
- `POST /pay` is not very RESTful. A more RESTful version might look something like `POST /payments` or `PUT /payments/:id` or `PUT /accounts/:username/payments/:payment_id` (is the payment a resource created under the account that you could then query later?)
- We might want to change `GET /spsp/:username` to `GET /accounts/:username/spsp`, since the SPSP details are a property of that account
- Should the balance endpoint be separate from the rest of the account details?

**Comment by bstrie** [comment]
> Should the balance endpoint be separate from the rest of the account details?

We could have a general endpoint for `GET /accounts/:username/:property`, which would give us `GET /accounts/:username/balance/`, plus e.g. `GET /accounts/:username/ilp_address`, `GET /accounts/:username/asset_code`, etc. We'd want to whitelist the properties visible to non-admins, of course. `GET /accounts/:username` could still get the full information for an account.

> We might want to change GET /spsp/:username to GET /accounts/:username/spsp, since the SPSP details are a property of that account

With the above suggestion, `GET /accounts/:username/spsp_address` would be natural.

> A more RESTful version might look something like...

...or, if we're feeling clever, `PUT /accounts/:username/balance`. :)

**Comment by gakonst** [comment]
I agree on the generic endpoint for each properties, did some initial work for it in #271. Which properties do we want to have available publicly?

I've changed /pay to /payments, and combined the balances in the account's details.

**Comment by emschwartz** [comment]
Why would `GET /accounts/:username/property` be more useful than a `GET /accounts/:username` that returns a JSON object with all of the properties? It seems like there's a decent chance that you'd want to see more than one property at a time. As for whether we should support both, I'd prefer to only have one if adding multiple methods doesn't add much new functionality.

**Comment by emschwartz** [comment]
> ...or, if we're feeling clever, PUT /accounts/:username/balance. :)

That wouldn't work because you'd need to `PUT` the total amount, rather than the delta, which would be a nightmare if you have different processes making payments at the same time.

**Comment by gakonst** [comment]
> Why would `GET /accounts/:username/property` be more useful than a `GET /accounts/:username` that returns a JSON object with all of the properties? It seems like there's a decent chance that you'd want to see more than one property at a time. As for whether we should support both, I'd prefer to only have one if adding multiple methods doesn't add much new functionality.

It might be better to make it `/accounts/:username?properties=ilp_address,balance` and make the server return only some of the data. Otherwise I'm find with pushing this responsibility client side.

**Comment by bstrie** [comment]
> Why would GET /accounts/:username/property be more useful than a GET /accounts/:username that returns a JSON object with all of the properties? It seems like there's a decent chance that you'd want to see more than one property at a time. As for whether we should support both, I'd prefer to only have one if adding multiple methods doesn't add much new functionality.

In the broader context this is about whether or not we should have an endpoint dedicated to getting the balance, which this philosophy would suggest we shouldn't.

Either way I think it would be nice to go through each account property and consider whether there are good reasons *not* to publicly expose any of them. If there are reasons to only expose certain properties to authenticated users, then we might want to consider having different endpoints for authenticated vs. unauthenticated users (or am I mistaken in the intent here, and *none* of these are intended to be public in the sense of being available to unauthenticated users?).

A different reason to consider individual endpoints rather than a single one is that it might make backward compatibility easier; even putting aside renaming or removing properties of an account, *adding* an API endpoint is never a problem whereas experience with Rust enums should demonstrate why adding new fields to something can sometimes introduce breakage for users (although if we expect most of our consumers to be using dynamic languages then this is less of an issue).

Another potential reason is ease of alternative implementations: I don't know how tightly-coupled our current response is to the AccountDetails struct, but I seem to recall @emschwartz noting that he thought that alternative implementations might have something entirely different internally (I didn't get clarification so I don't know how much of a problem he suspects this could be).

@gakonst's suggestion to have a single endpoint where users explicitly request certain properties via query parameters seems like it would give the benefits of having a single endpoint while still addressing the potential concerns above.

**Comment by bstrie** [comment]
> > ...or, if we're feeling clever, PUT /accounts/:username/balance. :)
>
> That wouldn't work because you'd need to PUT the total amount, rather than the delta, which would be a nightmare if you have different processes making payments at the same time.

Indeed, I should have written `PATCH` rather than `PUT`. :) But I'm fine with a payments being a noun on their own, it does seem like it could be useful to get a record of an individual payment (though this could be expressed as a property of an account, in which case there could be so much information that it may inform the discussion above about wholesale returning all account information).

**Comment by gakonst** [comment]
I've implemented the query string idea in https://github.com/interledger-rs/interledger-rs/pull/271/commits/27cb9ba72b72ed9615b0b27a031c1af0fb0874b9. This allows us to keep the old endpoint and add an optional query parameter `?properties=ilp_address,username,...` to fetch any specific fields. Net positive in the API functionality without adding any new functions. Private fields such as tokens etc. will not be able to be leaked via #245

**Comment by gakonst** [comment]
We've made a few changes already, do we intend to make more or can we close this?

**Comment by emschwartz** [comment]
I think we can close this. If we really want to combine the balance into the other account details, we can make that change later
