### ISSUE TITLE
Enforce minimum exchange rates

### ISSUE THREAD

**Issue by gakonst** [interledger-rs/interledger-rs#273]
> Also... when/if we add that exchange rate logic, we  _definitely_ need to fix this: https://github.com/interledger-rs/interledger-rs/blob/master/crates/interledger-stream/src/client.rs#L121

> Right now intermediary connectors can steal ALL the money!

_Originally posted by @kincaidoneil in https://github.com/interledger-rs/interledger-rs/issues/256#issuecomment-526635605_

**Comment by kincaidoneil** [comment]
FWIW, since we now have exchange rates within the store, this might be simple to fix. We'd somehow need the STREAM receiver to send a `ConnectionAssetDetails` frame when the connection is first created (since it's stateless, one approach would be to include it in response to any request with a `ConnectionNewAddress` frame). Then the client could lookup the rate from its asset to the destination asset, and determine a reasonable minimum destination amount.

**Comment by kincaidoneil** [comment]
Also, when we implement this, we need to update the STREAM sender to limit the delivered amount based on the minimum amount they set in the Prepare (the delivered amount should be the min of what the receiver claims they got, and what we told them was the minimum they should accept).

https://github.com/interledger-rs/interledger-rs/blob/748591691bf787bee8aafd380ac3d5c5872d82e5/crates/interledger-stream/src/client.rs#L306-L307

After we support invoices (paying by destination amount, rather than source amount), the recipient could fulfill the packet, but lie and say they received 0, which would cause the sender to continue sending indefinitely, draining their account.



JavaScript STREAM [is also vulnerable](https://github.com/interledgerjs/ilp-protocol-stream/blob/master/src/connection.ts#L1103)... but [Java is not](https://github.com/hyperledger/quilt/blob/0e5d69922722cd0458c2f5b6476aa2aa6e17a37b/stream-parent/stream-client/src/main/java/org/interledger/stream/sender/FixedReceiverAmountPaymentTracker.java#L143-L153)! Woot @sappenin 🎉 (although I think it would incorrectly report the delivered amount to the application)

**Comment by sappenin** [comment]
> although I think it would incorrectly report the delivered amount to the application

@kincaidoneil can you clarify that one? Is there a bug in the Java logic?

**Comment by sappenin** [comment]
@kincaidoneil this has been assigned to you - I think it's worth fixing.
