### ISSUE TITLE
Don't we need release notes?

### ISSUE THREAD

**Issue by dora-gt** [interledger-rs/interledger-rs#294]
Sometimes we have breaking changes on our new version.
Users might have difficulties in distinguishing what has been changed.
Also I think it is better to inform them about new features.

So don't we need release notes? though it might be cumbersome or too much in 0.x releases.

**Comment by gakonst** [comment]
Since we use conventional commits, we can use [conventional changelog](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-cli). I've used it in the past and it works nicely. We can also push it to CI with semantic-release: https://github.com/semantic-release/semantic-release

**Comment by gakonst** [comment]
Does #506 take care of that? @dora-gt

**Comment by dora-gt** [comment]
Yes, as long as we write commit logs properly, it will be shown on the release notes of GitHub releases. Let's see if it suffices. Revisit if there are any problems or possible improvements.
