### ISSUE TITLE
Improve Error types throughout the codebase

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/interledger-rs#317]
There are many places that we return `()` as the Error type from Futures, mostly because I was lazy and didn't want to have to figure out how to do it properly. We should go through the codebase and define proper error types as structs/enums.

As far as I understand, the core Error type has improved somewhat since when this project was started so I don't think we need to use an external crate like `failure` or `quick_error` anymore, though I could be wrong about this.

**Comment by dora-gt** [comment]
We really need this to give more precise error information.
If it means something of security matter, we could utilize server modes like `dev` or `production` or something. 

- `dev` = much information
- `production` -> less information

**Comment by emschwartz** [comment]
For this issues, I am mainly talking about returning better errors within the codebase. Each time we return an `Error = ()`, we should replace that with a more meaningful error. What we return via the API is slightly separate from that and I agree that we should be a little careful with how much detail we return to the caller

**Comment by dora-gt** [comment]
I meant, for example:
https://github.com/interledger-rs/interledger-rs/blob/master/crates/interledger-service/src/lib.rs#L117-L123
This is used from APIs, and I could not return something meaningful because () tells nothing. It ends up with just returning `Internal Server Error`s which is sometimes not so good for investigating what's happening.
