### ISSUE TITLE
Do the examples use too much dark magic?

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/interledger-rs#327]
I originally proposed using the literate programming style for the examples so that we could have markdown documentation that include code samples without needing separate bash files to make it easy to run the whole example at once. @dora-gt has done an awesome job executing on this idea. The issue now is that the examples have _a lot_ going on behind the scenes and our use of markdown + shell commands is getting pretty complicated.

Some of the specific things that add to the complexity behind the scenes:
- Setup and teardown
- Optionally using docker instead of building the project from source (and optionally using `sudo` for systems where docker must be run with it)
- Testing the markdown files to ensure our examples are up to date with code changes
- Running the markdown tests on CI (in both the docker and non-docker versions)

I'm not entirely sure this is a problem, but I'm opening this thread to discuss what we should do about this.

Some possibilities:
1. It's not a problem because it provides a good developer experience
2. We should turn our literate programming framework into a standalone project, document it, and make it clearer what it's doing under the hood and how you interact with it
3. We should get rid of the bash-based examples and replace them with examples in Rust so they can be run and tested using `cargo` (this has the downside of being less understandable to non-Rust developers)
4. Other

Thoughts?

**Comment by gakonst** [comment]
I think I'm more in favor of 2. 

We can have a new repo called `interledger-rust-tutorials` and move everything there. We could have a CI pipeline that runs the `.md` files as tests anytime there's a change in `master` of `interledger.rs`, and notifies us if we break something so that we make a PR for it. 

Also, what is the use of the `USE_DOCKER==1` branches in all our examples? Docker should be used by consumers of the repo as a way to easily run `interledger` or `interledger-settlement-engines`, don't think we should be doing anything in our tests with it?

e.g.
```
<!--!
printf "\nStarting Redis"
if [ "$USE_DOCKER" -eq 1 ]; then
    printf "\n"
    $CMD_DOCKER run --name redis-alice_node -d -p 127.0.0.1:6379:6379 --network=interledger redis:5.0.5
    $CMD_DOCKER run --name redis-alice_se -d -p 127.0.0.1:6380:6379 --network=interledger redis:5.0.5
    $CMD_DOCKER run --name redis-bob_node -d -p 127.0.0.1:6381:6379 --network=interledger redis:5.0.5
    $CMD_DOCKER run --name redis-bob_se -d -p 127.0.0.1:6382:6379 --network=interledger redis:5.0.5
else
    redis-server --version > /dev/null || error_and_exit "Uh oh! You need to install redis-server before running this example"
-->
``` 

in https://raw.githubusercontent.com/interledger-rs/interledger-rs/feature/dx/testable-md-integrating-into-ci/examples/eth-settlement/README.md#100

**Comment by emschwartz** [comment]
What's the benefit of moving it to a different repo? My thought on 2 was less about moving the tutorials themselves to a different repo and more about essentially moving the `run-md.sh` script to a different repo and documenting how it works better.

> Also, what is the use of the USE_DOCKER==1 branches in all our examples?

If you run the examples without docker, it can take a fairly long time to build. This was the motivation behind https://github.com/interledger-rs/interledger-rs/issues/179. The reason to test it also is to make sure we never break the examples

**Comment by dora-gt** [comment]
(Sorry for this late response)

In my opinion, examples show some "practical usecases". It requires:

1. Spinning up stores
1. Spinning up nodes
1. Setting up accounts
1. Retrieve private keys (and its public keys)
1. spinning up settlement engines

so... yes, this is "complicated". It's inevitable that the explanations and its scripts get complicated because what we are doing is complicated.
That said, we might be able to "focus" on some parts and separate things into different documents, which might simplify the situation. For example,

- We focus on normal mode (or Docker mode) in examples. This simplifies the scripts of the documents.
- We provide nice documents on our Docker images.
- We provide nice documents on the structure of node, store, settlement engines and other connectors.
- We provide nice documents on CLI parameters.
- We provide nice documents on setting up settlement engines.
- We provide nice documents on accounts.
- We provide nice documents on connecting to the testnet. (We already have though)

I think telling everything in only examples is difficult... or it is inappropriate. The structure should be:

- A nice foundation of explanation
- Examples on the foundation

We are building examples first, and no nice foundations are there. If we provide nice foundation, examples might not need too much information.

So my suggestion is:

- Remove docker mode (also provide nice documents on Docker images though)
    - Actually now that we have nice testnet bundle instead.
- Make `run-md` another project and provide documents on it. `sh`s are difficult to maintain.
- Construct a nice foundation on explanations

**Comment by dora-gt** [comment]
I'll keep thinking. I want to arrange my thoughts a bit more.

**Comment by dora-gt** [comment]
I think running tests on examples or documents is quite important. Many people ask me "Why doesn't this work?" or "I get an error when I do this". When I check the documents, in most cases, the cause is the recent change in command line arguments or something.

This is not good for two reasons:
1. Developers have difficulties in trying interledger-rs and they might feel uncomfortable with its experience.
1. We have to spend more time to support developers, answering their questions which could be avoided if we had provided more accurate documents.

We definitely should test documents.

**Comment by treisto** [comment]
The examples are like a receipt to follow. They are good to some extent, help starting-up.
At some point one needs to really understand how things work, what each setting means and does, what links where. In a different situation, it will be hard to debug or come up with a solution.

**Comment by emschwartz** [comment]
The examples are somewhat simpler now that we're using pre-built binaries instead of docker images. I'm going to close this for now, though we may want to reconsider how the examples work at some point in the future
