### ISSUE TITLE
Incoming and outgoing tokens should match

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/interledger-rs#357]
Right now the `ilp_over_btp_outgoing_token` has to be in the form `username:password` while the `ilp_over_btp_incoming_token` has to be in the form `password`. We should change it so both values can be exactly the same because it's way too confusing otherwise.

We should also make sure the same applies to `ilp_over_http`

**Comment by dora-gt** [comment]
I thought about this and I'm wondering which is the best approach:

1. Outgoing requests use "our" account username as the outgoing token username.
1. Split the outgoing token into `outgoing_token` and `outgoing_username`.
1. The incoming token includes an incoming username.

My opinion is "2" maybe.

1 is not good because the usernames might differ on our node and their node. (Or... should it be always a **relation name** like "node_a_b" or something? more confusing?)
2 might look a bit different from incoming tokens but it is inevitable because it represents another account on another node.
3 looks a bit redundant and confusing because it has another `username` though the account is clear already.

What do you think? @interledger-rs/contributors

**Comment by gakonst** [comment]
I am in favor of 2 with a slight twist:

1. Make the `outgoing_token` always be just the `token`, wihtout any password.
2. Make the `outgoing_username` optional. 
  - If it does not exist, it should use our `username`. This would require adding an extra parameter somewhere, probably on `InterledgerNode` config, which would be our Node's `username`.
  - If it exists, it should use that instead as the username.

**Comment by dora-gt** [comment]
Thank you @gakonst, what do you mean by "wihtout any password"?

**Comment by emschwartz** [comment]
Right now the whole thing we're doing with including the username in the token is pretty janky. I think we might want to fix that, along with making the configuration options clearer.

> Make the outgoing_token always be just the token, wihtout any password.

I think @gakonst meant username rather than password

> Make the outgoing_username optional

If this were provided, I would expect it to use basic auth instead of bearer token auth

**Comment by dora-gt** [comment]
@emschwartz Understood. One more question, do you mean, when the incoming service (HTTP/BTP) gets requests, it should be identified by ONLY the "token"?

I mean, the outgoing tokens should be used for "authentication" (identifying whose request it is) without usernames? Then, for example, `get_account_from_http_auth(username, password)` is going to be like `get_account_from_http_auth(access_token)`.

Then the tokens should be something very hardly conflicts with each other. Should we impose users to set the tokens in the format? though [RFC6750](https://tools.ietf.org/html/rfc6750#section-2.1) does NOT define its length, just saying it should be in the format of "b64token".

Or.... at least, it should not conflict on our store.

Sorry if I'm missing something.

**Comment by emschwartz** [comment]
No, that's what we had before but that was no good. Tokens shouldn't need to be globally unique.

Since we want to be able to identify which account a given request is for, the username definitely needs to be sent along with the request. The question is whether it should be included:
1. In the bearer token (`Authorization: Bearer username:token`)
2. As the username for basic auth (`Authorization: Basic dXNlcm5hbWU6dG9rZW4K`)
3. As a separate header

The reason we currently have `outgoing_token` as `username:token` is because that value is treated as opaque by the _sending_ node and simply put in the `Bearer` header. However, it's not great that the _receiving_ node is inspecting the token and expects it to be of the form `username:token`.

What I'm suggesting is that we may want to change this (it may be a breaking change) to get rid of the dark magic (token inspection), move the `username` to some clear and well-defined place as described above, and separate out the `outgoing_token` and `outgoing_username` as you described.

**Comment by dora-gt** [comment]
I see. Thank you for the description. I think we have one more option.

1. In the bearer token (Authorization: Bearer username:token)
1. As the username for basic auth (Authorization: Basic dXNlcm5hbWU6dG9rZW4K)
1. As a separate header
1. As a URL path segment
    - e.g. `https://xxx/accounts/:username/ilp`

I think getting the endpoint URL have `:username` also makes sense though this is a very big breaking change. I'm not so in favor of 1 and 2.

- Bearer token: basically it doesn't seem to expect that the token has something semantic like "username".
- Basic auth: it looks a bit inappropriate because Basic auth is usually used for a username:password pair.

The RFC says:

> HTTP does not restrict applications to this simple challenge-response framework for access authentication.  Additional mechanisms can be used, such as authentication at the transport level or via message encapsulation, and with additional header fields specifying authentication information.  However, such additional mechanisms are not defined by this specification.

So also an additional header seems legitimate.
Hmmm I think it should be 3 or 4. Maybe... 4? What do you think?

**Comment by dora-gt** [comment]
Or... could be BOTH for compatibility with the other implementations.

`IOH-Account-Username: xxxxx` (IOH=ILP over HTTP)

**Comment by emschwartz** [comment]
Good point about the URL. `/ilp` and `ilp/btp` are the only endpoints that deal with user-related concerns but don't have the username in the path. That option is tempting because then the actual auth can stay as simple bearer tokens and the caller/sender would treat the URL as opaque (as they always should) but it would include enough information for the node being called to look up the account record.

**Comment by dora-gt** [comment]
Do you mean, the other people (maybe attackers) could look up if the accounts exist or not?
Isn't it the same as the other APIs? We can respond always "Unauthorized" (not "Account not found"), and then they wouldn't know there is the account or not.

**Comment by emschwartz** [comment]
No, sorry, I meant just that if I tell you the ILP-over-HTTP URL for you on my system, you should treat that string as opaque (rather than me telling you the base URL and you assuming that the ILP-over-HTTP URL is the base + some specific path like `/accounts/:your-username/ilp`). That way, I can include whatever information I want in the URL (username, account ID, or other things) and you'll just use whatever URL I give you

**Comment by dora-gt** [comment]
Yes, I can imagine. Is that a problem? It seemed natural for me.

Ah so you mean, the counterpart node should always generate and give them the URL?

Hmm, maybe cumbersome sometimes but eventually they would give us the account username at least. So maybe there isn't so much difference. We could return endpoint URL when we created the account, if we want.

In addition, I feel connecting 2 nodes is difficult (creating accounts each other). We have to build some infrastructure to connect 2 nodes more easily, maybe.

**Comment by dora-gt** [comment]
I mean like:
- We build a server that conducts the connection of 2 nodes.
- The operator of Node A, B authorize that the server can create accounts on both nodes.
- The operator of Node A starts the procedure, inputting some information on the server.
- The operator of Node B gets notified that the Node A wants to connect.
- The operator of Node B accepts the connection.
- The server creates the accounts on both nodes.
There may be some security considerations but this is very easy to connect. We could also make it  more secure like we don't need to authorize the server to do something. We can export some appropriate settings to be imported both nodes instead.

**Comment by gakonst** [comment]
We're discussing 2 issues.

1. Where should we move the `username` that's part of the `outgoing_token` in the sending node, so that the incoming/outgoing token format matches
2. Where should the username go when a sending node sends a message to a receiving node.

For 1., what is the issue with the idea I proposed? I think it solves the format issue: https://github.com/interledger-rs/interledger-rs/issues/357#issuecomment-542483548

For 2: The goal is to avoid having the receiving node expect tokens in an encoded format with bearer auth. Options I'd consider which were proposed above:

1. Use Basic Auth, which is well specified. What is the issue with that? I forget.
2. Put the Username in the header. That also looks fine to me. The receiver can extract the username and the password from each header field separately. Makes the header a bit bigger though and I do not see how it provides meaningful advantages over Basic auth.
3. Customize the URL. Basically instead of calling `/pay`, we'd call `/pay/alice` and the receiving node would figure that's our username. Probably fine? I like that approach, but I do not think other connector implementations support that. 

Mostly in favor of Basic Auth, or the customized URL approach if we can make it compatible with other connector impls.

**Comment by dora-gt** [comment]
I moved this issue into Backlog because some people seem to be [trying to change BTP auth spec](https://interledger.slack.com/archives/CHQ9BCQ0Y/p1571237510024800). It seemed better to do this issue later.

That said, I thought we could change Part 1 (of the latest gakonst's comment) at this point but if we treat the outgoing token WITH the outgoing username as BASIC auth (as Evan said), it seems impossible without changing auth spec. (Sorry this may be a confusing expression)

I think the other implementations could also handle `/accounts/:username/ilp` style and I think this seems most clean way and makes sense in the `Bearer` token context. What about proposing this change?

**Comment by sappenin** [comment]
FWIW, I created #500 to add some context to the discussion here. I would advocate that the Rust implementation treat outgoing tokens as opaque in order to enable the token-creator (the "peer" in IlpOverHttp use-case, for example) complete control over the token format, meaning, etc.

This will reduce coordination between different implementations, and IMO make the Rust Account API clearer.

**Comment by emschwartz** [comment]
It does treat the outgoing token as opaque now -- with the exception that in the account settings API, the caller can change both tokens (which would cause a problem if the callee expects the token to have a specific format)

**Comment by sappenin** [comment]
> It does treat the outgoing token as opaque now
No, it parses the outgoing token and blows up if there's characters it doesn't expect. See #500

**Comment by emschwartz** [comment]
This will be done as part of #550
