### ISSUE TITLE
Settlement Utils Crate

### ISSUE THREAD

**Issue by gakonst** [interledger-rs/interledger-rs#435]
The following utils are used by the `settlement-engines` crate and the `interledger-settlement` crate:
- `Quantity`
- `scale_with_precision_loss`
- `IdempotentStore` (which currently is copied as `IdempotentEngineStore`
- `LeftoversStore`
- `Convert`
- `ConvertDetails`

The engines crate currently imports `interledger-settlement` to have access to most, or has a copy such as in the case of `IdempotentEngineStore`. 

I think these must be extracted to a separate shared crate, perhaps `interledger-utils`. We could also move the http errors that @dora-gt has in `interledger-http` in #324.

This would allow the `interledger-utils` crate to be imported by all crates which need to use
1. Errors
2. Idempotency
3. Asset scale conversions & precision loss store traits

We can also identify other functions, such as `get_hash_of` etc. which are repeated across the codebase and move them there (which we might already track in another issue)

**Comment by bstrie** [comment]
Would this subsume the `service-util` crate or would that still be separate?

**Comment by emschwartz** [comment]
Generally I'm not a fan of the idea of having an `interledger-utils` crate because it's likely to become a dumping ground for all kinds of miscellaneous functionality. The `interledger-service-utils` crate is _slightly_ more specific but I'd also like to get rid of it for the same reason.

How much code / how many of the dependencies in `interledger-settlement` are _not_ part of the shared utils? If it's not that much, couldn't we just use cargo features to turn off those other things so that the settlement engines can only import the part that's shared?

Another thought - if `interledger-settlement` is more closely related to the settlement engines than to the node, we could move it over to the other repo as well. It would make more sense to have a `settlement-utils` crate in the `settlement-engines` repo than a general `interledger-utils` one under `interledger-rs`.

I think it makes sense to keep the errors in `interledger-http`, at least for now, because they are specifically _HTTP_ errors.

**Comment by gakonst** [comment]
OK re:errors and `interledger-http`.

The features I want non-duplicated are the ones shared by `interledger-settlement` and `settlement-engines`. I thought of also moving settlement to the engines crate, and it is definitely an option. 

My only argument against it would be the idempotency utils could be useful in other idempotent API crates which we may(?) introduce in the future. 

I've [moved](https://github.com/interledger-rs/interledger-rs/pull/420/commits/dd4d8201d076fc89655157882bc96d205a492696) a few of the idempotency related utilities to `interledger-http`, since they're related to having idempotent HTTP APIs.

Can close this, what do you think about moving all settlement functionality to its own crate? It kind of makes sense, since we opt to run it in a separate port

**Comment by bstrie** [comment]
Generally agreed that "utility" crates should be avoided when possible.

**Comment by emschwartz** [comment]
> Can close this, what do you think about moving all settlement functionality to its own crate? It kind of makes sense, since we opt to run it in a separate port

Isn't it already in its own crate? Do you mean its own repo? 

> My only argument against it would be the idempotency utils could be useful in other idempotent API crates which we may(?) introduce in the future.

I'm not too worried about this right now. We don't have any current plans to add other idempotent APIs, though I agree we could do that in the future. However it wouldn't be that much work to extract it and put it somewhere else at that point so I'd go for what makes sense at the moment.

**Comment by gakonst** [comment]
Yeah I meant in its own repo. We could move `interledger-settlement` to the https://github.com/interledger-rs/settlement-engines repo as you pointed out in [the PR](https://github.com/interledger-rs/settlement-engines/pull/5#discussion_r336696856)

**Comment by gakonst** [comment]
Should've been clearer:
I meant "What do you think about making interledger-settlement a subcrate to the settlement-engines repository"?
