### ISSUE TITLE
What should we do with the `interledger_store_redis::Account` type?

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/interledger-rs#477]
Similar to https://github.com/interledger-rs/interledger-rs/issues/475, the `Account` type isn't specific to `Redis` and we will want to use it for each store implementation.

We should also consider merging the `Account` and the `interledger_api::AccountDetails` structs to avoid the current duplication.

I didn't put this type in the `interledger-service` crate initially because I thought that different stores might support accounts with different sets of fields. However, we will likely want all of the store implementations to support the same fields the API uses so the API can be used with any of them.

I'm not sure I want to move the `Account` into `interledger-service` now but if we did, I think it might remove around half of the generics (because each service is generic over the request type, which is generic over the account type).

**Comment by gakonst** [comment]
Based on our discussion from Rustfest, it seems like we are going to leave this as is? The AccountId change is now on master so that helped a bit with our services' generics.

Also, due to @bstrie's latest refactor, `Account` is no longer tied to the redis module, and shall be common to all backends we use. That said, should we close this?

**Comment by bstrie** [comment]
I think there's still a question of whether or not AccountDetails ought to be merged with Account (AccountSettings would remain separate and in the API).

**Comment by gakonst** [comment]
So if we merged them, we'd have to move `Account` from `interledger-store` to `interledger-api`.

In addition, we'd have to figure out a way for Serde to not require the caller to provide `id` when creating (because it must be generated by the node and not by the user) or modifying (because we do not want account-id's to be modifiable) an account.

Making the `id` field `Option` could be a choice, and make the `id` be generated via the `serialize_with` option of serde.

@bstrie is there a way to avoid making `id an `Option`?

**Comment by emschwartz** [comment]
Let's keep the `AccountDetails` separate from the `Account` for now. It's not the worst thing to have separation between the API schema and the DB schema.
