### ISSUE TITLE
The congestion controller's minimum value is 1, but if the sender sends a prepare packet with a value of 1, it MAY get a T04 error.

### ISSUE THREAD

**Issue by aanchal4** [interledger-rs/interledger-rs#513]
If the sender sends a prepare packet with a value of 1, there's a good chance that it will be rounded down (when the path exchange rates are applied) to 0. So the sender will be sending lots of packets but effectively not delivering anything. The following code for error T04.
https://github.com/interledger-rs/interledger-rs/blob/bd7ab9a9e86a158c61e4b9494d03bfbbbb700d55/crates/interledger-stream/src/congestion.rs#L114-L128

Potential solution 1: The reject packet can have a separate error code for such a situation (T05: minimum acceptable amount?), which would mean that the sender should increase/adjust the amount in the packet accordingly. 

A) This reject packet MAY indicate the details that the sender can use to compute the path exchange rate. It’s more in the vein of path exchange rate discovery [here](https://interledger.org/rfcs/0029-stream/#34-exchange-rates) and the STREAM packets already have that capability. The sender can then adjust the minimum value for the next prepare packet based on:
a) calculated exchange rate from reject packet, and 
b) minimum acceptable value for a prepare packet to be fulfilled.

https://github.com/interledger-rs/interledger-rs/blob/bd7ab9a9e86a158c61e4b9494d03bfbbbb700d55/crates/interledger-stream/src/client.rs#L84-L93

B) If the reject packet does not explicitly indicate the necessary details to compute the path exchange rate information (for some reason), then the sender can slowly start increasing the amount on the packets so as to see when it starts to get the fulfill packets again.
@emschwartz

**Comment by emschwartz** [comment]
Interledger allows sending 0-amount packets so I don't think we can or should rely on receiving an error here.

This is tricky because I think the T04 error is being caused by something else (not because the packet has an amount of 0). If the packet were reaching the STREAM server, I would say that the sender should use the `prepare_amount` in the STREAM response packet to figure out that 0 had been delivered to the receiver. But because something else is throwing a T04 first, it's not getting to the receiver.

:thinking:

**Comment by kincaidoneil** [comment]
> This is tricky because I think the T04 error is being caused by something else (not because the packet has an amount of 0). If the packet were reaching the STREAM server, I would say that the sender should use the prepare_amount in the STREAM response packet to figure out that 0 had been delivered to the receiver. But because something else is throwing a T04 first, it's not getting to the receiver.

This is a pretty bad issue, since if any two peers are configured with low credit limits such they need to settle during a STREAM payment, it will always fail since the congestion controller gets down to 1 and would never be able to ramp back up due to the rounding issue. (In practice, this triggers an R01 since the connector won't forward packets that round down to 0, and the payment fails even faster).

I think there's a neat solution to this:

Since the sender knows their minimum exchange rate and maximum slippage they'll allow for the path, they can calculate a _minimum_ source packet amount such that at least 1 unit arrives at the recipient. The cool thing about this is if any intermediary takes more slippage such that it rounds down to 0, it wouldn't matter, since it wouldn't meet the minimum destination amount and the recipient would reject it anyways.

In order of precedence, here's how each packet-amount-strategy would fit in:
1. Remaining amount to send (amount to send minus amount fulfilled and amount in-flight)
1. F08 maximum packet amount
1. Minimum source amount based on minimum exchange rate/slippage
1. Congestion controller maximum remaining in window

So, the minimum source amount would supersede the congestion controller's maximum in-flight amount, but not F08s or the remaining amount to send.

**Comment by kincaidoneil** [comment]
So, how might this minimum source packet amount be calculated?

Here's my model of this:

- `SCALED_RATE` &mdash; Factor to convert source amount to destination, between scales, and with slippage or a spread. For example, from scale 6 XRP to scale 9 ETH, with no slippage, this factor is `~1.035555` at current rates.
- `MARGIN_OF_ERROR` &mdash; Minimum percentage _difference_ between the sender's scaled rate and the connector's scaled rate (remember: both already include slippage!). For instance, if the sender and connector use exactly the same rate and slippage, the payment will likely always fail: the connector will round the decimal amount down, and the sender will round the decimal amount up when calculating the minimum destination amount. So, there must be some difference between these two scaled rates in order for the payment to succeed. The larger this difference is, the more "wiggle room" we have, and the more "wiggle room" we have, the smaller we can make the minimum source packet amount without it getting rounded down and rejected since it doesn't meet the minimum destination amount. _But_, if we set this margin of error or minimum percentage difference too low, we'd have to send massive packets, which would be bad.
- `source_amt * SCALED_RATE = dest_amt`
- `MARGIN_OF_ERROR = (ceil(dest_amt) - dest_amt) / dest_amt`

Conveniently, this simplified down to this inequality:
`source_amt > 1 / (SCALED_RATE * MARGIN_OF_ERROR)`

Example:
- The sender's scaled rate is `1.03555` (scale 6 XRP to scale 9 ETH)
- The sender's margin of error is `0.0001`. This means we're assuming the minimum scaled rate of the _connector_ to be `1.03555 + 0.0001`, or `1.03565`. (How we might choose this parameter is probably another discussion).
- Per the inequality above, our minimum source amount is `9656.65...`, which we'll round up to `9657`. This will be the amount for the packet.
- We'll also use our same scaled rate to calculate the minimum destination amount, so `9657 * 1.03555`, which is `10000.3063`, but we'll round up to `10001`.
- Suppose the connector's scaled rate actually is the minimum we're assuming it could be, `1.03565`. Now, when the intermediary will compute `9657 * 1.03565`, which is.... (drum roll) `10001.272`, which they'll round down to `10001`. Which means, _exactly enough_ got through to the recipient for them to fulfill the payment -- given these parameters/assumptions.

**Comment by sappenin** [comment]
> Potential solution 1: The reject packet can have a separate error code for such a situation (T05: minimum acceptable amount?)

FWIW, the Rust connector currently intercepts this condition and responds with an `R01` error (see [here](https://github.com/interledger-rs/interledger-rs/blob/ed83801bb90298b0adcd2b52c808fbca3745aeea/crates/interledger-service-util/src/exchange_rates_service.rs#L114)).

I point this out because this condition can be triggered by any intermediary in the payment path, with any variety of code. So, we can't rely on any particular ErrorCode to trigger this condition. Instead, I think the solution here needs be an implementation detail of the StreamSender.

**Comment by sappenin** [comment]
> So, the minimum source amount would supersede the congestion controller's maximum in-flight amount, but not F08s or the remaining amount to send.

I need to think through this a bit more, but this seems like a good solution.
