### ISSUE TITLE
SPSP Receiver Rejects final STREAM packet

### ISSUE THREAD

**Issue by sappenin** [interledger-rs/interledger-rs#68]
When making a STREAM payment to the SPSP receiver, it appears the SPSP receiver is rejecting the final STREAM packet (which is probably trying to close the STREAM).

For example, if an SPSP sender sends 1 units (in a  1-packet STREAM), then the first packet (Prepare with 1 units) works, and fulfills. But then there is a 2nd prepare (with amount=0), and the SPSP receiver always  rejects this packet with an `F99` error code. 

Note also that the `triggeredBy` in this reject packet is empty, but should be the ILP address of the SPSP receiver.

**Comment by emschwartz** [comment]
This happens because the `ConnectionClose` frame is sent separately from the last packet with money in it (see the code [here](https://github.com/emschwartz/interledger-rs/blob/develop/crates/interledger-stream/src/client.rs#L310)). It would be better if it recognized that a specific packet would be the last (assuming it's fulfilled) and send the closing frame with the last bit of money.

**Comment by kincaidoneil** [comment]
The STREAM sender uses a random condition in the packet with connection close frame, so it will always be rejected. I think this behavior is preferable to the final money packet, since there's no way to know for sure if that packet will be fulfilled -- you might need to try again.
