### ISSUE TITLE
Use `impl Trait` syntax where applicable

### ISSUE THREAD

**Issue by gakonst** [interledger-rs/interledger-rs#86]
In places such as https://github.com/emschwartz/interledger-rs/blob/es-settlement/crates/interledger-ccp/src/lib.rs#L100-L103 the `impl Trait` sugar can be used, which is much cleaner imo:

eg

```rust
fn set_routes<R>(&mut self, routes: R) -> Box<Future<Item = (), Error = ()> + Send>
where
    R: IntoIterator<Item = (Bytes, Self::Account)>;
```

into 

```rust
fn set_routes(
    &mut self,
    routes: impl IntoIterator<Item = (Bytes, Self::Account)>,
) -> Box<Future<Item = (), Error = ()> + Send>;
```

**Comment by bstrie** [comment]
Just to clarify, would we like to make it a matter of official style that all single-use generic input parameters are written using `impl Trait` form rather than the classic form, or do we prefer making the call on a case-by-case basis?

**Comment by emschwartz** [comment]
Any idea what's more common in other projects in the ecosystem?

I don't feel that strongly about this, so happy to go with whichever option improves readability or is more widely used.

**Comment by bstrie** [comment]
I wouldn't say that Rust projects in general tend to strictly adhere to this style, so for the moment I'll just focus on improving readability rather than seeking to enforce it everywhere. The places where it tends to have the biggest impact IMO are where it allows us to entirely get rid of the list of generic parameters, so I'll start with those.

**Comment by gakonst** [comment]
@emschwartz should we close this?
